server:
  port: 8502

spring:
  application:
    name: OrderService

  datasource:
    url: jdbc:mysql://localhost:3306/innovation
    username: root
    password: microserviceapp
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      automaticTransitionFromOpenToHalfOpenEnabled: true
      failureRateThreshold: 50
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowSize: 10
      waitDurationInOpenState: 10
      slidingWindowType: COUNT_BASED
  instances:
    backendA:
      baseConfig: default